# Generated by Django 2.0.1 on 2018-01-16 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='分类')),
                ('body', models.TextField(verbose_name='内容')),
                ('author', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='作者')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
