# Generated by Django 2.0.1 on 2018-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='图片ID')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
            ],
        ),
    ]
