# Generated by Django 2.0.1 on 2018-01-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=' ', upload_to='', verbose_name='图片'),
        ),
    ]
