# Generated by Django 2.0.1 on 2018-01-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='img_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='图片名称'),
        ),
    ]
