# Generated by Django 2.0.1 on 2018-01-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='图片ID'),
        ),
    ]
