# Generated by Django 2.0.1 on 2018-01-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_countview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countview',
            name='count_views',
            field=models.IntegerField(default='1', verbose_name='总浏览'),
        ),
    ]
