# Generated by Django 2.0.1 on 2018-02-02 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180131_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countview',
            name='the_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
